- test/test_endpoints.py
- txtorcon/endpoints.py
In case that the current hidden service dir is the same as the dir of any other hidden services, then change the current hidden service dir.
> Check whether current hidden service dir is the same as other hidden service dir

- test/test_torcontrolprotocol.py
- txtorcon/torcontrolprotocol.py
Added the descriptor get_info() test. The test presently fails and work needs to be done on the parse_keywords() and get_info() method for the test to pass. This will be reflected in the next commits.
> Added descriptor get_info() test

- docs/examples.rst
- examples/stem_relay_descriptor.py
Use stem Relay Descriptor class to parse the descriptor information. More about the stem class can be read at https://stem.torproject.org/api/descriptor/server_descriptor.html#stem.descriptor.server_descriptor.RelayDescriptor
> Use stem class for parsing relay descriptor

- docs/examples.rst
Currently, the docs under http://txtorcon.readthedocs.org/en/latest/examples.html#stem-relay-descriptor-py is broken and this PR fixes that.
> Fixed docs for stem_relay_descriptor.py

- test/test_torinfo.py
- txtorcon/torinfo.py
Implemented _get_descriptor() method
The parameters for the method are, `nickname`, `fingerprint`. These are the relay's nickname/fingerprint for which we want the descriptor information.
Returns the descriptor information. If use_stem is set to True, a `stem.descriptor.server_descriptor.RelayDescriptor` object is returned with the descriptor information.
> Parse desc/name and desc/id responses into Stem's RelayDescriptor class

- txtorcon/torconfig.py
key blobs can be between 820 and 825 bytes
> Fix EphemeralHiddenService key blob size constraint

- docs/releases.rst
- test/test_endpoints.py
- txtorcon/endpoints.py
This started out as making a test for the "success" path, but I ended up re-factoring the TorClientEndpoint to eliminate some state and use @inlineCallbacks instead of several _private_methods
Also some CamelCase to snake_case for function names etc.
@david415 what do you think?
> Endpoint tests and refactor

- docs/walkthrough.rst
In case you didn't already notice there is a small formatting error in the docs.
> Fix formatting in walkthrough

- test/test_torconfig.py
- txtorcon/torconfig.py
Hi
I noticed some bugs in the `TorConfig`:
* When saving boolean values the save call fails: 
```python
>>> config.AllowSingleHopCircuits = True
>>> config.save() # Fails because tor expects 0 or 1 not "True"
```
* When saving boolean values the saved value is not converted to boolean:
```python
>>> config = TorConfig(protocol)
>>> config.AllowSingleHopCircuits = 1
>>> config.save()
>>> config.AllowSingleHopCircuits
1
>>> config = TorConfig(protocol)
>>> config.AllowSingleHopCircuits
True
```
* When a `CONF_CHANGED` is received the value isn't parsed at all (tried after eea94c89407029ce0f1463e65c87a350ab8b9acc):
```python
>>> config.AllowSingleHopCircuits = True
>>> config.save()
>>> config.AllowSingleHopCircuits
True
>>> # some time passes
...
>>> config.AllowSingleHopCircuits
'1'
``` …
> Fix config value parsing issues 

- test/test_util.py
- txtorcon/torcontrolprotocol.py
- txtorcon/util.py
It would good to implement a function to unescapes strings according to the descriptions in the
[control spec (2.2.1)](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n110).
I tried to do this and define some tests.
> Correct string unescaping

- docs/releases.rst
- test/test_circuit.py
- txtorcon/circuit.py
The defaults for kwargs are computed at import time, which
was not the intent of this method when defaulting now=
> Fix circuit.age default-value

- docs/release-checklist.rst
- test/test_circuit.py
- test/test_stream.py
- test/test_torstate.py
- txtorcon/addrmap.py
- txtorcon/stream.py
- txtorcon/torstate.py
Using list-comprehensions to do the notifications might look nice, but isn't very robust.
Also, re-map Stream.target_host from IP back to hostname, whenever possible (should be "always").
> Addrmap stream improvement

- requirements.txt
Hello @meejah! Today I tried to install a newer version of txtorcon (from the cloned repo with `pip install -e`) and I had the following issue:
```
File "test.py", line 3, in <module>
import txtorcon  
File "/home/user/Desktop/txtorcon/txtorcon/__init__.py", line 16, in <module>
from txtorcon.controller import connect
File "/home/user/Desktop/txtorcon/txtorcon/controller.py", line 33, in <module>
from txtorcon.endpoints import TorClientEndpoint
File "/home/user/Desktop/txtorcon/txtorcon/endpoints.py", line 14, in <module>
from txtorcon.socks import TorSocksEndpoint
File "/home/user/Desktop/txtorcon/txtorcon/socks.py", line 18, in <module>
from twisted.protocols import tls
File "/home/user/Desktop/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 41, in <module>
from …
```
> Import `Twisted[tls]` and `automat`

- test/test_socks.py
- txtorcon/socks.py
These changes intend to make the improvement proposed in #214.
I made a very simple factory, inspired by the strings dictionary. What do you think?
I'd also like to know your opinion on the class names (specially `SucceededReply`).
I tried not to change things too much, so `_disconnect`  now expects `error_message` to be either a message or a code (would the name of the arg have to change?). If the code is found, it will instantiate the proper error. Otherwise it will be a `SocksError` with the message. That implies that if `error_message` is a code, there must exist a corresponding error because then the `SocksError` message will be just the code. Should it always be cast to `str`?
Do you think the factory should always create an error or just when it can actually create the specific …
> Create separate classes for each SOCKS error

- txtorcon/torconfig.py
As I was reading the specs recently, I noticed the following note and thought it wouldn't hurt to add this other conditional.
> Note: The incorrect spelling "Dependant" was used from the time
> this key was introduced in Tor 0.1.1.4-alpha until it was corrected
> in Tor 0.3.0.2-alpha.  It is recommended that clients accept both
> spellings.
Could this be useful?
> Accept `Dependent` for Tor >= 0.3.0.2-alpha

- docs/guide.rst
- docs/txtorcon-socks.rst
- docs/txtorcon.rst
- txtorcon/socks.py
I believe that mentioning these errors in the SOCKS5 section of the "Programming Guide" would be a good way to present them. I added the `socks` module to the docs containing only these errors because I needed a place for those classes and that looked like the right one to me. I'm not sure which other functions/classes we might want to add to this file because I think that module is a bit abstracted from the user and they might not touch those names. Is that right?
I did not add more details to the errors' docstrings but I will once I have a nice reference for that. For now I wrote that vague note until we have more info about the reasons for each error and tell the user they can find them in that module. (I should be able to do that during the week, so I think we can do everything with …
> Docs for SOCKS5 errors

- test/test_torconfig.py
- txtorcon/torconfig.py
These changes seem to fix #190 and implement a different check for the type and blob provided by the user.
Right now it only checks if the key contains a `':'` and in case the type is not `'NEW'`, makes sure the blob is not empty. Should we make sure both the type and blob are not empty? Also, as an extra `AttributeError` is being catched in case the user does not provide a string (well, something that does not `split`).
I am not sure about this, but I think it is a good practice to declare all attributes in `__init__`. Is it okay to declare `hostname` and `private_key` there (by just setting them to `None`)?
We should probably add tests for these too.
Let me know what you think. Thanks!
> Improve Ephemeral Onion Service private key handling

- txtorcon/torconfig.py
So, we are planning to release a new unMessage version and recently I have been working on a few things to prevent/handle errors that might frustrate users. When we configure the control port filter, everything works fine, but I forgot to handle when a filter prevents us from acquiring the process so users get a more friendly message.
It looks like the failure occurs in `torcontrolprotocol.py` at:
```python
811         eventnames = yield self.get_info('events/names')   
```
because that command is filtered and `log.err` at the end prevents this error from being handled. I do not fully understand the bootstrapping "magic" and I am not sure if this fix is actually a fix, but makes sense to me.
Is it correct?
P.S. I intend to handle an error with a `510` code. I am not too familiar to the …
> Errback when bootstrapping the `TorConfig`

- test/test_controller.py
- test/test_endpoints.py
- test/test_socks.py
- test/test_torconfig.py
- txtorcon/controller.py
- txtorcon/torconfig.py
Handle all the `*PortLines` options properly, and also handle defaults better overall.
> Port line defaults

- docs/releases.rst
- examples/web_onion_service_ephemeral_unix.py
- test/test_controller.py
- txtorcon/onion.py
Parsers allow local ports to be unix-sockets; this lets ephemeral and non-ephemeral services listen
over unix sockets (so long as the tor we're connected to
supports that).
> onions on unix sockets

- docs/releases.rst
- examples/web_onion_service_endpoints.py
- test/test_endpoints.py
- test/test_onion.py
- txtorcon/controller.py
- txtorcon/endpoints.py
- txtorcon/onion.py
- txtorcon/torconfig.py
...and an `await_all_uploads` option when launching Onion services (instead of just waiting for one).
> Onion progress improvements

- txtorcon/controller.py
On Ubuntu we don't ship controller_py3.py for Python 2.7 because parsing it during installation breaks the installation.
The missing file triggers ModuleNotFoundError instead of SyntaxError and IMO catching Exception and continuing with no async is semantically as correct as listing the potential subclasses.
> figure out if we have async in an even more robust way

- docs/releases.rst
- examples/web_onion_service_ephemeral_nonanon.py
- test/test_endpoints.py
- test/test_onion.py
- txtorcon/controller.py
- txtorcon/endpoints.py
- txtorcon/onion.py
See #315 
"launch()" should probably support the right option(s) too, but .. tor doesn't bootstrap if you start it with the two relevant options but *without* any Onion Services defined on the command-line as well (see https://github.com/meejah/txtorcon/pull/318 for that implementation thus far).
See https://trac.torproject.org/projects/tor/ticket/27849 which is the "tor doesn't bootstrap" bug described above.
> non anonymous services

- docs/releases.rst
Put this to the correct base. Thank for your help @meejah !!
> Ticket284 when disconnected docs release notes

- test/test_controller.py
- test/test_endpoints.py
- txtorcon/controller.py
Easy enough start to check for 'Opening Control listener' over checking every line for bootstrap. Edited the tests. Next steps could be parsing only a few lines?
Do we need to error handle when control port is not set?
Thanks
> Ticket226 control port status

- txtorcon/controller.py
- txtorcon/torconfig.py
Quick fix for the abc change in 3.8.
Please let me know etiquette wise where a try block like this should go for imports.
> Adding support for 3.8 abstract base classes

- txtorcon/torstate.py
> Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

- test/test_util.py
> Use a different name to avoid triggering trial's skip logic

- docs/introduction.rst
It's an implementation of Bitcoin CoinJoin, a technique to improve the confidentiality and privacy of Bitcoin transactions. Have been using txtorcon since November 2018.
> Mention JoinMarket in "Known Users" list

- docs/releases.rst
- test/test_web.py
- txtorcon/circuit.py
- txtorcon/controller.py
- txtorcon/interface.py
- txtorcon/web.py
> Add the ability to override HTTPS TLS context

- docs/conf.py
- docs/guide.rst
- docs/installing.rst
- docs/release-checklist.rst
- docs/releases.rst
- examples/web_client.py
- test/test_endpoints.py
- test/test_stream.py
- test3/test_controller.py
- txtorcon/controller.py
- txtorcon/endpoints.py
It seems examples and documentation are still using the old onion address v2.
With this pull request i'm updating them to the current v3 address.
> Update onion address used for documentation

- docs/releases.rst
- test/test_torcontrolprotocol.py
- txtorcon/torcontrolprotocol.py
- txtorcon/util.py
> hanging GETINFO

- dev-requirements.txt
- doc-requirements.txt
- test/py3_test_controller.py
- test/test_attacher.py
- test/test_circuit.py
- test/test_controller.py
- test/test_endpoints.py
- test/test_onion.py
- test/test_router.py
- test/test_socks.py
- test/test_torconfig.py
- test/test_torstate.py
- test/test_util.py
- test/test_web.py
- test3/test_controller.py
- tox.ini
Since Python 3.3 mock is now also provided by unittest so a dependency on mock is no longer required.
> test: mock is now a build in Python module

- examples/web_onion_service_endpoints.py
- test/test_endpoints.py
- test/test_torconfig.py
- txtorcon/circuit.py
- txtorcon/controller.py
- txtorcon/endpoints.py
- txtorcon/onion.py
- txtorcon/router.py
- txtorcon/socks.py
- txtorcon/testutil.py
- txtorcon/torconfig.py
- txtorcon/torcontrolprotocol.py
- txtorcon/util.py
- txtorcon/web.py
`defer.returnValue` was only needed in Python 2; in Python 3, a simple `return` is fine.
`twisted.internet.defer.returnValue` is deprecated as of Twisted 24.7.0.
> Stop using twisted.internet.defer.returnValue
