docs/walkthrough.rst
=> Fixed broken link under docs for NEWNYM

test/test_torconfig.py, txtorcon/torconfig.py
=> HiddenServiceDir should be absolute. Test also added

test/test_torconfig.py, txtorcon/torconfig.py
=> Check multiple hidden services with same directory

README.rst
=> Added OSX installation instructions

test/test_torcontrolprotocol.py
Fixed the Stem version tests that were failing earlier.
=> Fixed the failing stem tests

test/test_torcontrolprotocol.py, txtorcon/torcontrolprotocol.py
Changes made in the PR:
* The data received in `got_update()` is now added with the response code and the event name. The end of each line of the data is added with `\r\n`
* The `response_data` is then parsed into the `ControlMessage` class of Stem and is then converted to the subclass using `stem.response.convert`.
TODO:
* The converted `response_data` should be passed to `cb()` appropriately.
=> Convert event into Stem class

txtorcon/torcontrolprotocol.py
Changes made in the PR:
* Uses StringIO.StringIO now in place of string concatenation for generating event data for Stem
=> Use StringIO for generating event data for Stem

txtorcon/endpoints.py
=> Teach tor endpoint to only return ConnectionRefusedError

test/test_circuit.py, test/test_torstate.py, txtorcon/__init__.py, txtorcon/circuit.py
- builds circuits within a given timeout duration
I still need to add tests and make sure the cancellation works as expected. Perhaps you'd like to code review it now?
=> Add build_timeout_circuit helper function

INSTALL, README.rst, dev-requirements.txt, docs-requirements.txt, docs/releases.rst, requirements.txt, test/test_util.py, test/test_util_imports.py, tox.ini, txtorcon/util.py
=> use ipaddress instead of ipaddr

docs/releases.rst, test/test_torcontrolprotocol.py, txtorcon/torcontrolprotocol.py
https://github.com/meejah/txtorcon/issues/174
=> Add support for NULL control port authentication

test/test_torconfig.py, txtorcon/torconfig.py
That is, if a user passes a config with ControlPort set to "unix:/some/path" then we need to connect to that (instead of pretending it's always a port-number)
=> Issue 187: Correctly identify unix ControlPort

txtorcon/circuit.py, txtorcon/torconfig.py
Just a small one after running `tox -e flake8` on `HEAD`.
=> Add flake8 recommended style changes.

README.rst
=> Add libgeoip-dev note.

test/test_microdesc.py, test/test_torstate.py, txtorcon/_microdesc_parser.py, txtorcon/torstate.py
replace the `spahgetti.FSM` parser with an Automat one.
=> Microdesc automat parser

test/test_router.py, test/test_torcontrolprotocol.py, txtorcon/router.py, txtorcon/torcontrolprotocol.py
=> Event listener errors

examples/connect.py, examples/disallow_streams_by_port.py, examples/dns_lookups.py, examples/launch_tor.py, examples/launch_tor_endpoint.py, examples/launch_tor_unix_sockets.py, examples/web_client.py, examples/web_client_custom_circuit.py, examples/web_client_treq.py
cosmetic change to the examples
=> react(main) -> @react

examples/readme3.py, test/py3_torstate.py, test/test_controller.py, test/test_socks.py, test/test_torstate.py, test/test_web.py, tox.ini, txtorcon/socks.py, txtorcon/torcontrolprotocol.py, txtorcon/torstate.py, txtorcon/util.py
Note to self: look at fixing maybeDeferred in Twisted instead...
=> make stream-attacher (and other user-callbacks) work properly with async/await

examples/launch_tor.py, examples/launch_tor_unix_sockets.py, examples/readme.py, examples/readme3.py, examples/stream_circuit_logger.py, examples/web_client_custom_circuit.py, test/test_controller.py, test/test_endpoints.py, txtorcon/__init__.py, txtorcon/controller.py, txtorcon/endpoints.py, txtorcon/interface.py, txtorcon/torconfig.py
This was spurred by #123 and is also related to #215
=> 123 client endpoint constructors

test/test_controller.py, test/test_endpoints.py
(not sure why master *isn't* failing on travis though ...)
=> test fixups

test/test_endpoints.py, txtorcon/controller.py, txtorcon/torconfig.py
=> 227 control socks port launch

txtorcon/torconfig.py
=> work around incremental bug

txtorcon/torconfig.py
Here is an option to what we discussed in #230.
It looks a bit redundant to me and all could be turned into a setter, but not sure if that's a good idea and `_is_valid_keyblob` might be useful one day for other things (what also makes me think if it should be public instead).
What do you think?
=> Convert key-blob with `nativeString` for ASCII/unicode compatibility

test/test_endpoints.py, txtorcon/endpoints.py
=> Fix parsing of GETCONF outside TorConfig

test/test_endpoints.py, txtorcon/endpoints.py
This is https://github.com/meejah/txtorcon/pull/246 with an improved test on top
=> 245 multiple connect

docs/releases.rst, test/test_controller.py, txtorcon/controller.py
See also #251 which this partially solves
=> add Tor.is_ready and Tor.become_ready

docs/releases.rst, test/test_torcontrolprotocol.py, test/test_torstate.py, txtorcon/torcontrolprotocol.py, txtorcon/torstate.py, txtorcon/util.py
=> unit-test and fix for deleted routers

requirements.txt, setup.py
Note, this requires a build version of setuptools greater than 36.2.
=> Make ipaddress a conditional dependency.  (Closes: #247)

docs/installing.rst
=> add note about 'invalid syntax'

setup.py
Don't pollute `site-packages` with a local `test` module.
=> Don't install global test package

test/test_onion.py, txtorcon/onion.py
=> Issue290 keyblob whitespace

docs/releases.rst, txtorcon/torstate.py
See also https://tests.reproducible-builds.org/debian/rb-pkg/buster/amd64/txtorcon.html
=> Get rid of eventmap

docs/releases.rst, test/test_torstate.py, txtorcon/circuit.py, txtorcon/torstate.py
=> David415 errors build circuit

docs/releases.rst, test/test_torcontrolprotocol.py, txtorcon/torcontrolprotocol.py
=> Ticket284 when disconnected

docs/releases.rst, test/test_controller.py, txtorcon/controller.py, txtorcon/onion.py
=> Ticket315 non anonymous services  launch.1

docs/releases.rst
Just add documentation to release.rst for the changes to collections.abc import.
=> Release note comment for collections.abc

docs/releases.rst, test/test_util.py
=> Use real geoip database

.travis.yml, tox.ini
=> add python 3.7, 3.8 and twisted 20

.github/workflows/flake8.yaml, .github/workflows/python2.yaml, .github/workflows/python3.yaml, .github/workflows/readme_render.yaml, docs/releases.rst, test/test_util.py, tox.ini, txtorcon/torinfo.py
=> 350.attribute error

test/test_web.py
=> Avoid triggering any trial skip logic when no skip is intended

test/test_endpoints.py
=> Provide signature-compatible ``launch`` fakes and more-initialized configs

test/test_endpoints.py
Some leftover updates while looking at  #356
=> test-failure updates

requirements.txt
=> no more ipaddress

.github/workflows/python3.yaml, README.rst, docs/releases.rst, setup.py, tox.ini
=> Add explicit support for newer Python 3 versions

docs/releases.rst, test/test_torstate.py
=> make tests more-specific

doc-requirements.txt, requirements.txt
This pull request removes the unused dependency `incremental` from the `requirements.txt` and `doc-requirements.txt` configuration files. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.
The `incremental` library was first introduced to the project in 0a1fc13. However, in #234, the usage of `incremental.Version` was substituted with a custom `_Version` class.  This internal implementation effectively replaced the functionalities that were previously sourced from the library. Given this, the `incremental` dependency appears to be extraneous and isn't required anymore. Removing this unused dependency reduces the overall footprint of the application, mitigating potential security risks, and simplifying …
=> Remove Unused Dependency: Incremental

tox.ini
See #396 which reveals this breakage
=> workaround for coverage breakage

.github/workflows/python3.yaml, docs/releases.rst, test/test_torconfig.py, tox.ini
See https://github.com/NixOS/nixpkgs/pull/335112#issuecomment-2294363299
=> Twisted 24.7.0 fixes
